name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Zip the project
        run: zip -r lambda-deploy.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: my-node-lambda
          zip-file: lambda-deploy.zip
          aws-region: ap-south-1
          role: arn:aws:iam::039612874091:role/node-cicd-role
